//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageProduct
    {
        public int IdProductImage { get; set; }
        public int IdProduct { get; set; }
        public byte[] ImageSource { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
