//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ImageProduct = new HashSet<ImageProduct>();
        }
    
        public int IdProduct { get; set; }
        public string ProductName { get; set; }
        public int IdCategory { get; set; }
        public int IdUnitOfMeasurement { get; set; }
        public int IdManufacturer { get; set; }
        public decimal CostPerUnit { get; set; }
        public decimal RoundPrice
        {
            get
            {
                return Math.Round(CostPerUnit);
            }
        }
        public string Description { get; set; }
        public Nullable<int> Qty { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageProduct> ImageProduct { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual UnitOfMeasurement UnitOfMeasurement { get; set; }
    }
}
