//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_InfoProduct
    {
        public int IdProduct { get; set; }
        public string ProductName { get; set; }
        public string Category { get; set; }
        public string UnitOfMeasurement { get; set; }
        public string Manufacturer { get; set; }
        public decimal CostPerUnit { get; set; }
        public string Description { get; set; }
        public Nullable<int> Qty { get; set; }
    }
}
